# Generated by Django 5.0.4 on 2024-08-07 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumo", models.PositiveIntegerField()),
                ("fecha_registro", models.DateTimeField(auto_now=True)),
                ("nota", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ralada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("cantidad_bastones", models.PositiveIntegerField()),
                ("peso_inicial", models.PositiveIntegerField()),
                ("sobra_inicial", models.PositiveIntegerField()),
                ("sobra_final", models.PositiveIntegerField()),
                ("peso_final", models.PositiveIntegerField()),
                ("fecha_registro", models.DateTimeField(auto_now=True)),
                ("fecha_llega", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoGuarana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProduccionDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha_registro", models.DateTimeField(auto_now=True)),
                (
                    "produccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.produccion",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producciones",
                        to="core.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="produccion",
            name="ralada",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produccion",
                to="core.ralada",
            ),
        ),
        migrations.CreateModel(
            name="Saco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_registro", models.DateTimeField(auto_now=True)),
                ("fecha_llega", models.DateTimeField(auto_now=True)),
                (
                    "tipo_guarana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sacos",
                        to="core.tipoguarana",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ralada",
            name="saco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raladas",
                to="core.tipoguarana",
            ),
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_venta", models.DateTimeField(auto_now=True)),
                ("fecha_registro", models.DateTimeField(auto_now=True)),
                (
                    "metodo_pago",
                    models.ManyToManyField(related_name="ventas", to="core.metodopago"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VentaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fecha_venta", models.DateTimeField(auto_now=True)),
                ("fecha_registro", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.venta",
                    ),
                ),
            ],
        ),
    ]
