# Generated by Django 5.1 on 2024-08-12 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompraVidros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_gasto', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('C', 'Cartão'), ('D', 'Dinheiro'), ('P', 'Pix')], default='C', max_length=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Metodo de Pago',
                'verbose_name_plural': 'Metodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': '- Producciones',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_llega', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGuarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Variedad de Guarana',
                'verbose_name_plural': 'Variedades de Guarana',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_inventario', models.DateField(default=django.utils.timezone.now)),
                ('anotaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierre_inventarios', to='core.anotacioninventario')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.produccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_consumo', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, null=True)),
                ('productos', models.ManyToManyField(related_name='consumo', to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='anotacioninventario',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones_inventario', to='core.producto'),
        ),
        migrations.CreateModel(
            name='Ralada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_bastones', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('sobra_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('sobra_final', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_final', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_ralada', models.DateField(default=django.utils.timezone.now)),
                ('produccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ralada', to='core.produccion')),
                ('saco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ralada', to='core.saco')),
            ],
        ),
        migrations.AddField(
            model_name='saco',
            name='tipo_guarana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sacos', to='core.tipoguarana'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('compra_vidros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='core.compravidros')),
                ('metodo_pago', models.ManyToManyField(related_name='ventas', to='core.metodopago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='UsoMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('declarado', models.BooleanField(default=False)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_metodo_pago', to='core.metodopago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_metodo_pago', to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.venta')),
            ],
            options={
                'verbose_name': 'Item Vendido',
                'verbose_name_plural': 'Items Vendidos',
            },
        ),
    ]
