# Generated by Django 5.0.4 on 2024-08-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produccion",
            name="ralada",
        ),
        migrations.AddField(
            model_name="ralada",
            name="produccion",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ralada",
                to="core.produccion",
            ),
            preserve_default=False,
        ),
    ]
