# Generated by Django 5.1 on 2024-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_fabricado',
            field=models.BooleanField(default=False),
        ),
    ]
