# Generated by Django 5.0.4 on 2024-08-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_produccion_ralada_ralada_produccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produccion",
            name="consumo",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="cantidad_bastones",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="numero",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="peso_final",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="peso_inicial",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="sobra_final",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="sobra_inicial",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
