# Generated by Django 5.1 on 2024-08-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_es_fabricado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
    ]
