# Generated by Django 5.0.4 on 2024-08-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_produccion_consumo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produccion",
            name="consumo",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="cantidad_bastones",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="numero",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="peso_final",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="peso_inicial",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="saco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raladas",
                to="core.saco",
            ),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="sobra_final",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="sobra_inicial",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
