# Generated by Django 5.1 on 2024-08-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usometodopago',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
