# Generated by Django 5.1 on 2024-08-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usometodopago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_items', to='core.producto'),
        ),
    ]
