# Generated by Django 5.0.4 on 2024-08-07 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_produccion_consumo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ralada",
            name="fecha_llega",
        ),
        migrations.RemoveField(
            model_name="ventaitem",
            name="fecha_venta",
        ),
        migrations.AddField(
            model_name="ralada",
            name="fecha_ralada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 7, 15, 27, 46, 71179, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="saco",
            name="fecha_llega",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 7, 15, 27, 46, 70597, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="saco",
            name="peso",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha_venta",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 7, 15, 27, 46, 69529, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
