# Generated by Django 5.0.4 on 2024-08-07 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_ralada_fecha_llega_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ralada",
            name="fecha_ralada",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="saco",
            name="fecha_llega",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha_venta",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
