# Generated by Django 5.1 on 2024-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ventaitem_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
