# Generated by Django 5.0.4 on 2024-08-08 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_ralada_fecha_ralada_alter_saco_fecha_llega_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metodopago",
            options={
                "verbose_name": "Metodo de Pago",
                "verbose_name_plural": "Metodos de Pago",
            },
        ),
        migrations.AlterModelOptions(
            name="produccion",
            options={
                "verbose_name": "Produccion",
                "verbose_name_plural": "- Producciones",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoguarana",
            options={
                "verbose_name": "Variedad de Guarana",
                "verbose_name_plural": "Variedades de Guarana",
            },
        ),
        migrations.AlterModelOptions(
            name="venta",
            options={"verbose_name": "Venta", "verbose_name_plural": "- Ventas"},
        ),
        migrations.AlterModelOptions(
            name="ventaitem",
            options={
                "verbose_name": "Item Vendido",
                "verbose_name_plural": "Items Vendidos",
            },
        ),
        migrations.AlterField(
            model_name="ralada",
            name="saco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raladas",
                to="core.saco",
            ),
        ),
    ]
