# Generated by Django 5.1 on 2024-08-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producciondetalle',
            name='peso_producido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
