# Generated by Django 5.0.4 on 2024-08-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_metodopago_options_alter_produccion_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ventaitem",
            old_name="precio_unitario",
            new_name="precio",
        ),
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=13.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ralada",
            name="saco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ralada",
                to="core.saco",
            ),
        ),
    ]
