# Generated by Django 5.1 on 2024-08-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_tipo_guarana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producciondetalle',
            name='peso_producido',
        ),
    ]
