# Generated by Django 5.0.4 on 2024-08-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_producto_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
