# Generated by Django 5.0.4 on 2024-08-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_producto_precio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venta",
            options={"verbose_name": "Venta", "verbose_name_plural": "Ventas"},
        ),
        migrations.AlterField(
            model_name="ventaitem",
            name="precio",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
