# Generated by Django 5.1 on 2024-08-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_producciondetalle_peso_producido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compravidros',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
    ]
