# Generated by Django 5.1 on 2024-08-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_compravidros_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usometodopago',
            name='venta',
        ),
    ]
