# Generated by Django 5.1 on 2024-08-10 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_venta_options_alter_ventaitem_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_metodo_pago', to='core.metodopago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_metodo_pago', to='core.venta')),
            ],
        ),
    ]
