# Generated by Django 5.1 on 2024-08-10 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usometodopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraVidros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='compra_vidros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='core.compravidros'),
        ),
    ]
