# Generated by Django 5.1 on 2024-08-10 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_compravidros_venta_compra_vidros'),
    ]

    operations = [
        migrations.AddField(
            model_name='compravidros',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compravidros',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('C', 'Cartão'), ('D', 'Dinheiro'), ('P', 'Pix')], default='C', max_length=1),
        ),
    ]
