# Generated by Django 5.1 on 2024-08-11 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_compravidros_fecha_compra_compravidros_nota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_gasto', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnotacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones_inventario', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_consumo', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, null=True)),
                ('productos', models.ManyToManyField(related_name='consumo', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_inventario', models.DateTimeField(default=django.utils.timezone.now)),
                ('anotaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierre_inventarios', to='core.anotacioninventario')),
            ],
        ),
    ]
