# Generated by Django 5.1 on 2024-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_gasto_anotacioninventario_consumo_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usometodopago',
            name='declarado',
            field=models.BooleanField(default=False),
        ),
    ]
