# Generated by Django 5.1 on 2024-08-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_usometodopago_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='compra_vidros',
        ),
        migrations.AddField(
            model_name='compravidros',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_vidros', to='core.venta'),
        ),
    ]
