# Generated by Django 5.1 on 2024-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['tipo_guarana', '-peso', 'nombre'], 'verbose_name': 'ModelName', 'verbose_name_plural': 'ModelNames'},
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='core_produc_tipo_gu_2c3482_idx',
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo_guarana', '-peso', 'nombre'], name='core_produc_tipo_gu_d9325f_idx'),
        ),
    ]
