# Generated by Django 5.1 on 2024-08-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_periodo_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='acvito',
            new_name='activo',
        ),
    ]
