# Generated by Django 5.1 on 2024-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_acvito_periodo_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['precio', 'tipo_guarana', '-peso', 'nombre'], 'verbose_name': 'ModelName', 'verbose_name_plural': 'ModelNames'},
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='core_produc_tipo_gu_d9325f_idx',
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio', 'tipo_guarana', '-peso', 'nombre'], name='core_produc_precio_d770a6_idx'),
        ),
    ]
